name: ludo_club
description: Ein modernes Ludo Club Spiel
version: 1.0.0+1
environment:
  sdk: ">=2.17.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.3
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.0
  intl: ^0.18.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
